# Generated by Django 4.1.3 on 2024-06-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, null=True)),
                ('product_type', models.CharField(max_length=50, null=True)),
                ('cost', models.IntegerField(null=True)),
                ('popularity', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
